# Conclusion

## Exploration
In this project, we have analyzed the unemployment rate along the time since 2012 based on the data we retrieved from the U.S. Bureau of Labor Statistics (BLS) website, and we have paid more attention to the recent three years. 

As for the state-level unemployment rate, we find that the job market has shown evidence for recovery during the recent three years after Covid-19, in terms of the median of unemployment rate of each state. To compare each state’s unemployment rate with each other in the three periods listed as Oct 2019 - Sep 2020, Oct 2020 - Sep 2021, and Oct 2021 - Sep 2022, the Cleveland dot plot told us the order between average monthly unemployment rate between states almost stayed the same during those three periods. Nevada yielded the highest unemployment rate (>12.5%) due to the burst of the Covid-19 pandemic during Oct 2019 - Sep 2020, and then Hawaii, Michigan, California, and New York in decreasing order. Also, South Dakota yielded the lowest unemployment rate at around 4%. As time went by, the unemployment rate for all states dropped, except for Connecticut. The average unemployment rate in Connecticut between October 2020 and September 2021 was even higher than that between October 2019 and September 2020. Until September 2022, most states had applied policies to lower their average unemployment rate for the recent 12 months below 5%. In addition, these three periods all reveal a pattern that some specific parts of the US, including western, southern, and northeastern states, suffered more severe unemployment than states in other parts. It might be due to the fact that in these parts, the economy has been more developed. Therefore, when the economy suffers, the volatility will be relatively large. 

As for race, during the most recent year from Sept 2021 to Sept 2022, Black Americans suffered the highest unemployment rate during this period, which was twice as much as the unemployment rate of either White Americans or Asian Americans.In addition, we can notice that before January 2022, the unemployment rate of Asian Americans was higher than White Americans, while White Americans displayed a higher unemployment rate than Asian Americans after January 2022. 

To explore how unemployment situations are related to different ages over various periods, we can see from the stacked bar graph that the unemployed population contains most people at 55 ages or more, then 25-34, 35-44, 45-54, 20-24, 18-19, 16-17 in the decreasing order. Notice that the number of unemployed people between the ages of 16 and 24 is relatively small, compared to that of the population over 24. However, the unemployment rate is much higher among people between 16 and 24 than people over 24. It is explainable since the total labor force of young people (16 to 24) is relatively smaller. Many people at this age are still at school. Also, with the economic recovery, the unemployment rate for employers in most age intervals reached a very low level. However, the unemployment rate for young people aged from 16 to 24 is still high. It is because the economy has just recovered, and many companies need some time to return to the economic level before Covid-19. Thus, they may not have enough money and efforts to hire and train young employees. In addition, the proportion of high unemployment population groups is higher among people over 35 years old, making workers less than 35 years old face a less difficult unemployment situation than those over 35 years old. There can be multiple explanations for this phenomenon. For example, the cardinality of working people over 35 years old could be larger than those under 35 years old.

As for sex, we can see from the unemployment rate charts that the ratio between male unemployment and female unemployment has been close to 1:1 since 2019. It implies that unemployment after Covid-19 does not affect each gender more or less. This phenomenon could be explained by the fact that sex discrimination in the labor market has been paid more attention to by more companies, and employment does not give preference to each gender. However, when we divide the population into two age groups: <35 years old, and >=35 years old, for both age intervals, the proportion of highly unemployed groups is more significant in males than females. 

Last but not least, we want to see the unemployment situation from a broader perspective, that is, GDP and CPI. For both before and after Covid-19 period, CPI is negatively associated with the unemployed population. In other words, a higher CPI can be associated with a lower unemployed population, and vice versa. However, during the past ten years, several high CPI and large unemployed population data were all from the After-Covid period (see the top left part of the parallel coordinate plot). We can infer that the Covid-19 pandemic resulted in severe inflation and job loss, significantly impacting people’s lives. Also, the unemployed population is negatively associated with GDP in both Pre-Covid and After-Covid periods. That is, a higher unemployed population corresponds to a lower GDP. In the past ten years, most GDP values after Covid-19 were still higher than before Covid-19, indicating that generally speaking, GDP in the U.S. had grown gradually in the past ten years. However, due to the enormous impact of the Covid-19 pandemic, several pieces of GDP data were lower than some Pre-Covid GDP values and connected with high unemployed population data.

Generally speaking, we have to admit the fact that the unemployment situation did get worse after Covid-19 burst out. As you know, many departments have spared no effort to work on the unemployment situation since the 2008 financial crisis, and the unemployment rate has shown a satisfying trend since 2012, and before Jan 2020, the unemployment rate has reached 3.5%, which is very close to the ideal point. However, years of hard word became nothing overnight when the pandemic came. The unemployment rate suddenly soared and became 14.7% in April 2020. Obviously with the effort of many departments, the unemployment rate decreases along the time. And much to our delight, the unemployment rate reaches 3.7% in November 2022. It is almost close to the point before Covid-19. 

## Limitations

Firstly, we use different data to represent the unemployment situation for analysis on different features due to different formats of retrieved data. For example, we use unemployment rate when analyzing state,  while we use unemployed population when analyzing age and sex. It might cause some barriers if we want to analyze several features together. 

Second, some labels of our visualization could be not clear enough. For example, there are some overlapping issues especially for tick mark labels on the x axis. 

Thirdly, some thresholds we choose during data preprocessing for visualization could be more reflective and reliable if we were given more time. For example, in the mosaic plot, we divide the unemployment population into three groups: low, medium and high. However, in the column representing women less than 35 years old, there is no medium unemployed population; similarly, in the column representing women more than 35 years old, there is no low unemployed population. 

Fourth, during the process of creating d3 visualization, our group members have struggled a lot to create an accurate y scale for the bar plot. We design a function to update our y axis every time we select a state according to the state data. And we want the heights of the columns in our bar plot changed accordingly so that they matched. However, we did not expect that it was not an easy job to make two scaleLinear() matches. We have tried different coefficients to scale the domain, while none of them worked. To reduce the impact of this issue, we created a label for each bar that would show the unemployment rate whenever your mouse moved on it. 

Fifth, at the beginning, we wanted to design a map and a bar plot that is associated with the dropdown list on the top of our page. After we select a state from the dropdown list, the dot whose size represents the unemployment rate of the selected state in September 2022 is supposed to become red, instead of blue. However, we have tried many times, and we get to the point where the ever-selected state’s color stays red and never returns back to blue when we select another state, which is close to, but not what we want. 

## Future directions

On one hand, given more time, we want to make our visualizations better, solving the limitations we list above. On the other hand, we also want to explore how the unemployment situation has changed in different industries and which industry has been affected the most by the pandemic. It will be very interesting and also related to our graduate student’s life. For example, was the high-tech industry affected by the pandemic? How much has the pandemic affected the high-tech industry? Is this phenomenon related to the recent hiring freeze situation? In addition, if there is available data, we want to zoom in on every industry and observe the unemployment situation from the company level. 

## Lessons learned

First, we learned multiple technical skills of exploratory data analysis and visualization. After finishing this project, we could proficiently leverage the power of R and its packages. With a great amount of time put into this project, we have obtained a deeper understanding of the use of each type of graph and stronger abilities to generate insights from various charts. The use of D3 also develops our skill sets that we learned how to interactively display the data to our audience. 

Second, we learned several soft skills that may be beneficial for our future career or life. Our teamwork skills and problem-solving skills are greatly cultivated through the nature of this collaborative project, which we may experience more and more when we get into industry. 

Through this final project, we developed both technical skills and soft skills which will certainly benefit our future life.   
