--- 
title: "Exploring Unemployment Conditions in the United States After Covid-19"
author: "Kaiyuan Liu (kl3447), Zhuolin Luo (zl2852), Yizhan Niu (yn2440)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

With the Covid-19 virus fading away from our lives, we are gradually entering the post-pandemic era. It seems that our lives are getting back on track to the pre-pandemic levels. However, the impact of the pandemic on the global economy, especially on the labor market, has not completely disappeared. According to the Lead Editor of Forbes Advisor Benjamin Curry, “inflation hit a 40-year high of 9.1%” in 2022, which was seen as an aftershock of the pandemic. (cited from https://www.forbes.com/advisor/investing/why-is-inflation-rising-right-now/) 
	To better understand whether our economy has recovered from this pandemic, we would like to estimate the impact of Covid-19 on the labor market by analyzing unemployment conditions two years after the pandemic. As an indicator of economic health, the unemployment rate can effectively reflect how the overall market performs. Is the economy in this country in a recessionary period or an expansionary period? Are most people in the labor market having trouble finding a new job? A well-established analysis of unemployment can help us better answer these questions. 
	There are five aspects we will dig deep into in order to comprehend the unemployment condition in the US after the pandemic. First, we would like to know how the unemployment rate has changed over the past ten years to see whether the time-series chart shows us any patterns during and after Covid-19. Second, we would like to know how the unemployment condition of each state changes over time in the US. Third, we want to investigate the intensity of the impacts unemployment has on each race group. Fourth, we want to see the influence of the pandemic on the unemployment rate in the groups of each age interval and both genders. Finally, we will compare the unemployment rate with GDP and CPI data to understand the unemployment condition in the context of the economy on a macro scale. By putting the unemployment rate in the context of time, location, race, age, gender, and economy, we can better understand the impact of the pandemic on the economy in general two years after the outbreak of Covid-19.  